"""Tools for querying Rucio subscriptions."""

from __future__ import annotations

from typing import Annotated, Any

from mcp.server.mcpserver import Context, MCPServer  # noqa: TC002
from mcp.types import CallToolResult, TextContent, ToolAnnotations
from pydantic import BaseModel

from rucio_mcp.tools._helpers import (
    RULE_LIST_KEYS,
    build_hints,
    classify_error,
    format_list,
    get_rucio_client,
    paginate_iter,
)


class RucioListSubscriptionsResult(BaseModel):
    """Structured result of ``rucio_list_subscriptions``."""

    name: str
    account: str
    subscriptions: list[dict[str, Any]]
    offset: int
    limit: int
    truncated: bool


class RucioSubscriptionRule(BaseModel):
    """One replication rule generated by a subscription."""

    id: str | None = None
    state: str | None = None
    rse_expression: str | None = None
    account: str | None = None
    copies: int | None = None
    expires_at: str | None = None
    locks_ok_cnt: int | None = None
    locks_replicating_cnt: int | None = None
    locks_stuck_cnt: int | None = None


class RucioListSubscriptionRulesResult(BaseModel):
    """Structured result of ``rucio_list_subscription_rules``."""

    account: str
    name: str
    rules: list[RucioSubscriptionRule]
    offset: int
    limit: int
    truncated: bool


def register(mcp: MCPServer) -> None:
    """Register subscription tools with the MCP server."""

    @mcp.tool(
        annotations=ToolAnnotations(
            title="List subscriptions", read_only_hint=True, open_world_hint=True
        )
    )
    async def rucio_list_subscriptions(
        name: str = "",
        account: str = "",
        limit: int = 100,
        offset: int = 0,
        *,
        ctx: Context[Any, Any],
    ) -> Annotated[CallToolResult, RucioListSubscriptionsResult]:
        """List Rucio subscriptions, optionally filtered by name or account.

        Subscriptions are automated rules that watch for new DIDs matching a
        filter and automatically create replication rules for them.

        Args:
            name: Subscription name to filter by. If empty, all subscriptions
                are returned.
            account: Account that owns the subscriptions to filter by.
            limit: Maximum number of subscriptions to return (default 100).
            offset: Number of subscriptions to skip for pagination.
        """
        client = get_rucio_client(ctx)
        try:
            it = client.list_subscriptions(
                name=name or None,
                account=account or None,
            )
            results, footer = paginate_iter(it, limit=limit, offset=offset)
        except Exception as exc:  # noqa: BLE001
            return classify_error(exc)

        if not results:
            return CallToolResult(
                content=[TextContent(type="text", text="No subscriptions found.")],
                structured_content=RucioListSubscriptionsResult(
                    name=name,
                    account=account,
                    subscriptions=[],
                    offset=offset,
                    limit=limit,
                    truncated=False,
                ).model_dump(mode="json"),
            )

        hints = build_hints(
            [
                (
                    "Use `rucio_list_subscription_rules <account> <name>` to see "
                    "rules generated by a subscription"
                )
            ]
        )
        text = format_list(results) + footer + hints
        payload = RucioListSubscriptionsResult(
            name=name,
            account=account,
            subscriptions=results,
            offset=offset,
            limit=limit,
            truncated=bool(footer),
        )
        return CallToolResult(
            content=[TextContent(type="text", text=text)],
            structured_content=payload.model_dump(mode="json"),
        )

    @mcp.tool(
        annotations=ToolAnnotations(
            title="List subscription rules", read_only_hint=True, open_world_hint=True
        )
    )
    async def rucio_list_subscription_rules(
        account: str,
        name: str,
        limit: int = 100,
        offset: int = 0,
        *,
        ctx: Context[Any, Any],
    ) -> Annotated[CallToolResult, RucioListSubscriptionRulesResult]:
        """List replication rules generated by a specific subscription.

        Args:
            account: Account that owns the subscription.
            name: Subscription name.
            limit: Maximum number of rules to return (default 100).
            offset: Number of rules to skip for pagination.
        """
        client = get_rucio_client(ctx)
        try:
            it = client.list_subscription_rules(account, name)
            results, footer = paginate_iter(it, limit=limit, offset=offset)
        except Exception as exc:  # noqa: BLE001
            return classify_error(exc)

        if not results:
            return CallToolResult(
                content=[
                    TextContent(type="text", text="No rules found for this subscription.")
                ],
                structured_content=RucioListSubscriptionRulesResult(
                    account=account, name=name, rules=[], offset=offset, limit=limit,
                    truncated=False,
                ).model_dump(mode="json"),
            )

        hints = build_hints(
            ["Use `rucio_get_replication_rule <rule_id>` to see full details of a rule"]
        )
        text = format_list(results, include_keys=RULE_LIST_KEYS) + footer + hints
        payload = RucioListSubscriptionRulesResult(
            account=account,
            name=name,
            rules=[RucioSubscriptionRule(**r) for r in results],
            offset=offset,
            limit=limit,
            truncated=bool(footer),
        )
        return CallToolResult(
            content=[TextContent(type="text", text=text)],
            structured_content=payload.model_dump(mode="json"),
        )
