"""Tools for querying Rucio subscriptions."""

from __future__ import annotations

from typing import Any

from mcp.server.fastmcp import Context, FastMCP  # noqa: TC002

from rucio_mcp.tools._helpers import (
    RULE_LIST_KEYS,
    build_hints,
    classify_error,
    format_list,
    get_rucio_client,
    paginate_iter,
)


def register(mcp: FastMCP) -> None:
    """Register subscription tools with the MCP server."""

    @mcp.tool()
    async def rucio_list_subscriptions(
        name: str = "",
        account: str = "",
        limit: int = 100,
        offset: int = 0,
        *,
        ctx: Context[Any, Any],
    ) -> str:
        """List Rucio subscriptions, optionally filtered by name or account.

        Subscriptions are automated rules that watch for new DIDs matching a
        filter and automatically create replication rules for them.

        Args:
            name: Subscription name to filter by. If empty, all subscriptions
                are returned.
            account: Account that owns the subscriptions to filter by.
            limit: Maximum number of subscriptions to return (default 100).
            offset: Number of subscriptions to skip for pagination.
        """
        client = get_rucio_client(ctx)
        try:
            it = client.list_subscriptions(
                name=name or None,
                account=account or None,
            )
            results, footer = paginate_iter(it, limit=limit, offset=offset)
        except Exception as exc:  # noqa: BLE001
            return classify_error(exc)

        if not results:
            return "No subscriptions found."

        hints = build_hints(
            [
                "Use `rucio_list_subscription_rules <account> <name>` to see "
                "rules generated by a subscription"
            ]
        )
        return format_list(results) + footer + hints

    @mcp.tool()
    async def rucio_list_subscription_rules(
        account: str,
        name: str,
        limit: int = 100,
        offset: int = 0,
        *,
        ctx: Context[Any, Any],
    ) -> str:
        """List replication rules generated by a specific subscription.

        Args:
            account: Account that owns the subscription.
            name: Subscription name.
            limit: Maximum number of rules to return (default 100).
            offset: Number of rules to skip for pagination.
        """
        client = get_rucio_client(ctx)
        try:
            it = client.list_subscription_rules(account, name)
            results, footer = paginate_iter(it, limit=limit, offset=offset)
        except Exception as exc:  # noqa: BLE001
            return classify_error(exc)

        if not results:
            return "No rules found for this subscription."

        hints = build_hints(
            ["Use `rucio_get_replication_rule <rule_id>` to see full details of a rule"]
        )
        return format_list(results, include_keys=RULE_LIST_KEYS) + footer + hints
