{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rucio-mcp.fullname" . }}
  labels:
    {{- include "rucio-mcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rucio-mcp.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
